# Workflow : 하나의 yml 파일을 하나의 Worrkflow로 본다.
name: Github Actions 실행시켜보기 #Workflow의 이름

on:
  push:
    branches:
      - main  # main 브랜치에 push 이벤트 발생 시 아래 Workflow를 실행합니다

jobs:
  My-Deploy-job:
    runs-on: ubuntu-latest  # Github Actions를 실행시킬 서버 종류 선택

    steps:
      - name: Hello World 찍기  #Step에 이름 붙이는 기능
        run: echo "Hello World"  #실행할 명령어

